os:
  - linux
  - osx
language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq librecode-dev
  - sudo apt-get build-dep enca
  - sudo pip install cpp-coveralls --use-mirrors
script: 
  - ./autogen.sh --with-gcov && make && make test
after_success:
  - coveralls
addons:
  coverity_scan:
    project:
      name: "nijel/enca"
      description: "Build submitted via Travis CI"
    notification_email: michal@cihar.com
    build_command_prepend: "./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan
matrix:
  allow_failures:
    - os: osx
